# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-16 21:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20170116_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='description',
        ),
        migrations.RemoveField(
            model_name='images',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='images',
            name='upload_date',
        ),
        migrations.AlterField(
            model_name='images',
            name='imgfile',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
    ]
