# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 19:50
from __future__ import unicode_literals

from django.db import migrations, models
import gallery.models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_images_imgfile_mini'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='imgfile_mini',
            field=models.FileField(blank=True, upload_to=gallery.models.user_directory_path2),
        ),
    ]
