# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-26 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_auto_20170126_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
